version: '3'

services:
   php:
    build:
      context: ./
    container_name: container_php
    ports:
      - "8080:80"
    networks:
      - mysql_default
    volumes:
      - ./:/var/www/html

networks:
  mysql_default:
    external:
      name: mysql_default
